<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>68fa11a7-7c4e-4c2d-8c14-0c8e2bcdffb0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Billetterie.Application\Billetterie.Application.csproj" />
    <ProjectReference Include="..\Billetterie.Infrastructure\Billetterie.Infrastructure.csproj" />
  </ItemGroup>

</Project>
